package service

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"regexp"
)

// Errors returned by the service package.
var (
	ErrUnknownService  = errors.New("unknown service")
	ErrUnsupportedLink = errors.New("unsupported link")
	ErrLocalLink       = errors.New("local links are not supported")
	// ErrNotImplemented means the service is recognized but its data extractor is
	// not ported yet. The architecture allows adding a helper for it.
	ErrNotImplemented = errors.New("service helper not implemented")
)

// localLinkRe matches local URLs (file://, localhost, 127.*, 192.168.*) that the
// VOT API cannot translate. Ported from @vot.js/core/utils/videoData.js.
var localLinkRe = regexp.MustCompile(`(file://(/)?|(http(s)?://)(127\.0\.0\.1|localhost|192\.168\.(\d){1,3}\.(\d){1,3}))`)

// VideoData is the resolved metadata for a video, consumed by the VOT client.
type VideoData struct {
	URL             string
	VideoID         string
	Host            string
	Title           string
	Duration        float64
	Subtitles       []Subtitle
	TranslationHelp []TranslationHelp
}

// Subtitle is an external subtitle track discovered while resolving video data.
type Subtitle struct {
	Language        string
	Source          string
	Format          string
	URL             string
	IsAutoGenerated bool
}

// TranslationHelp points Yandex at a raw video / subtitles file to aid translation.
type TranslationHelp struct {
	Target    string
	TargetURL string
}

// Fetcher is the minimal HTTP interface used by service helpers.
type Fetcher interface {
	Do(req *http.Request) (*http.Response, error)
}

// GetService returns the first registered service matching the URL, or nil.
// Local links always return nil.
func GetService(rawURL string) *Service {
	if localLinkRe.MatchString(rawURL) {
		return nil
	}
	u, err := url.Parse(rawURL)
	if err != nil || u.Hostname() == "" {
		return nil
	}
	for i := range sites {
		if sites[i].Match != nil && sites[i].Match(u) {
			return &sites[i]
		}
	}
	return nil
}

// GetVideoData resolves the full video data for a URL: it detects the service,
// extracts the video id and, when required, fetches extra data (duration, raw
// url). Ported from @vot.js/node/utils/videoData.js.
func GetVideoData(ctx context.Context, f Fetcher, rawURL string) (*VideoData, error) {
	if f == nil {
		f = http.DefaultClient
	}
	svc := GetService(rawURL)
	if svc == nil {
		return nil, fmt.Errorf("%w: %q", ErrUnknownService, rawURL)
	}
	u, err := url.Parse(rawURL)
	if err != nil {
		return nil, err
	}

	var videoID string
	if h, ok := helpers[svc.Host]; ok && h.id != nil {
		videoID, err = h.id(ctx, f, u)
		if err != nil {
			return nil, err
		}
	} else if svc.Host == HostCustom {
		videoID = u.String()
	} else {
		return nil, fmt.Errorf("%w: %s", ErrNotImplemented, svc.Host)
	}
	if videoID == "" {
		return nil, fmt.Errorf("%w: %q", ErrUnsupportedLink, rawURL)
	}

	origin := u.Scheme + "://" + u.Host
	baseURL := svc.BaseURL
	switch svc.Host {
	case HostPeertube, HostCoursehunterLike, HostCloudflareStream:
		baseURL = origin
	}

	if svc.RawResult {
		return &VideoData{URL: videoID, VideoID: videoID, Host: svc.Host}, nil
	}
	if !svc.NeedExtraData {
		return &VideoData{URL: baseURL + videoID, VideoID: videoID, Host: svc.Host}, nil
	}

	h, ok := helpers[svc.Host]
	if !ok || h.data == nil {
		return nil, fmt.Errorf("%w: %s requires extra data fetching", ErrNotImplemented, svc.Host)
	}
	res, err := h.data(ctx, f, svc, origin, videoID)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, fmt.Errorf("failed to get video data for %s", svc.Host)
	}
	res.VideoID = videoID
	res.Host = svc.Host
	return res, nil
}
